package tailscale

import (
	"github.com/coredns/coredns/plugin"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// tailscaleHostsEntries is the combined number of entries.
	tailscaleHostsEntries = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: plugin.Namespace,
		Subsystem: "tailscale",
		Name:      "entries",
		Help:      "The combined number of entries generated by Tailscale devices.",
	}, []string{})
	// tailscaleHostsReloadTime is the timestamp of the last reload of the records by Tailscale API.
	tailscaleHostsReloadTime = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: plugin.Namespace,
		Subsystem: "tailscale",
		Name:      "reload_timestamp_seconds",
		Help:      "The timestamp of the last reload by Tailscale API.",
	})
)
